blackuy/react-native-twilio-video-webrtc

src/TwilioVideo.android.js
On android we are using findNodeHandle to get the view to send commands
to but depending on the specifics of the layout, 'this' may not refer
to what we want.
=> Use findNodeHandle on the inner view on android

package.json, src/TwilioVideo.android.js, src/TwilioVideo.ios.js, src/TwilioVideoLocalView.ios.js, src/TwilioVideoParticipantView.ios.js
React 16.0.0 is still in alpha. But newest version of react-native already uses it so it makes sense to merge this PR probably
=> fix(propTypes): add react >16.0.0 support

android/src/main/java/com/twiliorn/library/TwilioPackage.java
createJSModules is no longer present.  In order to ensure backwards
compatibility, just remove the Override tag for now.
=> Fix android build for RN 0.47

src/TwilioVideo.android.js
The way we are passing events along in the android side, the callbacks
would receive and event object.  However, the interface expects the
underlying nativeEvent (i.e. a map with the fields as on iOS), so we
need to put together simple wrappers for our events to make things
match.
Fixes #29
=> Fix handling of android events

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
* Previously this was bombing if there was no view attached for the
local camera when calling switchCamera.  Now it gracefully ignores the
command.
* Create a function to set the correct flip and call it in the right
places so that we don't get funky behaviors depending on the ordering
between the camera switch and the mounting of the local view.
=> A few switchCamera fixes

ios/RCTTWVideoModule.m
Currently the local view does not do any mirroring of the video.
However, you nearly always want the front camera to be mirrored.  This
adds that logic on the iOS side so that it automagically happens (this
behavior already exists on Android).
=> Improved camera mirroring behavior on iOS

Example/index.ios.js
> Error: One of the sources for assign has an enumerable key on the prototype chain. This is an edge case that we do not support. This error is a performance optimization and not spec compliant.
`Object.assign` and `Object.keys` should not be used with `Map`. I was seeing errors when trying this example on the latest RN release.
=> Fix errors when using `Object` apis with `Map`

ios/RCTTWVideoModule.m, src/TwilioVideo.ios.js
Simply a flag "screenShare" passed to TwilioVideo that causes the video track to use TVIScreenCapturer instead of TVICameraCapturer.
I can take a look at having a toggle that replaces the video track in a future PR, but all I needed for my immediate project was screensharing.
=> feature-screencap Add flag to TwilioVideo to use TVIScreenCapturer (iOS only)

ios/RCTTWLocalVideoViewManager.m, ios/RCTTWRemoteVideoViewManager.m
There are some cases where react native's dynamic resizing of the views
directly causes problems.  Wrapping the views within plain UIViews
seems to solve the problem.
Additionally, this allows us to set the contentMode on the video views
to AspectFill which will replicate the behavior that was recently
merged into android.
=> [iOS] Embed video views within parent views

.gitignore, android/build.gradle, android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java, android/src/main/java/com/twiliorn/library/RNVideoViewGroup.java, android/src/main/java/com/twiliorn/library/TwilioPackage.java, android/src/main/java/com/twiliorn/library/TwilioRemotePreview.java, android/src/main/java/com/twiliorn/library/TwilioRemotePreviewManager.java, android/src/main/java/com/twiliorn/library/TwilioVideoPreview.java, android/src/main/java/com/twiliorn/library/TwilioVideoPreviewManager.java, src/TwilioVideoParticipantView.android.js
This merge request was initiated by @georgewwindsor and I simply squashed the commits.. Also, added a small change to TwilioVideoParticipantView.android.js where the trackId prop was required
Below is the original message from #74 
The existing android code uses a single "participantTrack" to contain incoming tracks. This causes 2 problems:
1. current android code is only 1-to-1.
2. the current android code gets" disconnected" from the server because it screws up the bitrate when you replace the video with the next incoming person.
I have modified the library to allow multiple android users on stage at once. This required routing the trackId through the android component, which was previously not being done.
i additionally updated the android TWILIO dependency from 1.0.1 to 1.3.8 …
=> Android multiparty support implemented by @georgewwindsor

src/TwilioVideoParticipantView.android.js
For consistency's sake the track ID should be passed as part of the track identifier prop.
I've set this up so that both the previous ad hoc prop and the ios compatible prop will work now.
=> Make trackId on android match iOS

.gitignore, README.md, ios/RCTTWLocalVideoViewManager.h, ios/RNTwilioVideoWebRTC.xcodeproj/project.pbxproj
As amazingly useful as this project has been for me, it has caused serious issues in using with Fastlane and my Podfile while having `use_frameworks` enabled.
So, I created an XCode project for this library, which (in my opinion) simplifies the setup on iOS.
If you choose to merge this, the setup process will be something like this:
1. Add `pod 'TwilioVideo'` to your Podfile
2. Add `RNTwilioVideo.xcodeproj` to the Libraries directory in your project
3. Add `libRNTwilioVideo.a` to the "Linked Frameworks and Libraries"
A further improvement would be to make it so you can just run `react-native link react-native-twilio-video-webrtc` and it performs the 3 steps above.
=> Enable use without adding to Podfile

README.md
The docs had a button press handler that wasn't actually wired up to anything.  This makes it up to date to match the actualy example in the repo.
=> Update docs for flip camera

ios/RCTTWVideoModule.m, src/TwilioVideo.ios.js
This is an implementation of getStats on iOS that mostly conforms to the interface initially proposed in #84 and should conform entirely to #91.  I've tried, however, to
a.) Clean up the code quite a bit with helper functions.
b.) Omit the constraints related changes (I feel that we can land that separately without issue).
=> getStats for iOS

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java, src/TwilioVideo.android.js
This is an implementation of getStats for Android.  It pretty much mirrors the room.getStats call, builds the data structure, and passes it along via an onStatsReceived event.
This more or less comports with current iOS branch implementing the same functionality.
=> getStats for Android

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java, src/TwilioVideo.android.js
Per discussion here:
https://github.com/twilio/video-quickstart-android#troubleshooting-audio
and here:
twilio/video-quickstart-android#221
On some devices it may be advisable to disable openSL ES.  This PR exposes that functionality.
=> Function to disable OpenSL ES on Android

react-native-twilio-video-webrtc.podspec
The current podspec rule will match 2.x versions.  While there's a branch in progress for TwilioVideo2 support, master doesn't yet support it.  Consequently, this PR changes the dependency rule to use optimistic versioning which should ensure that it stays in 1.x.
=> Update twiliovideo dependency version

android/build.gradle, android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java, android/src/main/java/com/twiliorn/library/TwilioRemotePreview.java, android/src/main/java/com/twiliorn/library/TwilioRemotePreviewManager.java, src/TwilioVideo.android.js, src/TwilioVideoParticipantView.android.js
This updates the interface to work with Twilio Video v2.1.  In addition to a bunch of general cleanup, it updates the events to be more similar to their iOS counterparts.  The same user changes needed to get things working on iOS should also work here (namely, the use of Sids to identify everything).
=> Support on Android for Twilio Video v2

ios/RCTTWRemoteVideoViewManager.m, ios/RCTTWSerializable.m, ios/RCTTWVideoModule.m, react-native-twilio-video-webrtc.podspec, src/TwilioVideo.ios.js, src/TwilioVideoParticipantView.ios.js
This PR updates the library to support version 2.2 of the Twilio Video library.  It does not yet expose any new functionality per-se of v2 of the library; the goal here is feature parity with minimal changes for existing users of the library.
The main user-visible changes are:
* `onParticipant{Enabled/Disabled}Track` are now broken out into separate events for Audio and Video.
* The track identifier prop type now contains two fields: `participantSid` and `videoTrackSid`.  Generally under the hood we try to use sids everywhere as the idenfitier for participants and tracks.  This would necessitate a small change in the example, namely in the `onParticipantAddedVideoTrack` handler set:
```
this.setState({
participant,
track,
});
```
and then pass this in as follows:
``` …
```
=> Support Twilio Video 2.2 on iOS

android/build.gradle
Check rootProject for compileSdkVersion, buildToolsVersion, targetSdkVersion, and androidSupportVersion, with defaults as fallback.
Also including gradle updates from @slycoder 
1. Use implementation instead of compile.
2. Get rid of the test depencies for now since we don't have any android tests to speak of.
3. Get rid of an unneeded library which was causing conflicts with newer appsupport libraries.
=> Update gradle and use rootProject variables

android/src/main/java/com/twiliorn/library/TwilioRemotePreviewManager.java, android/src/main/java/com/twiliorn/library/TwilioVideoPreviewManager.java, ios/RCTTWLocalVideoViewManager.m, ios/RCTTWRemoteVideoViewManager.m, src/TwilioVideoLocalView.ios.js, src/TwilioVideoParticipantView.ios.js
Creates scaleType prop for use in either TwilioVideoParticipantView or TwilioVideoLocalView. 
Use 'fit" to scale video render to original proportions. Default remains "fill", which crops the video to fill the entire screen.
=> adds scaleType prop for rendering participant and local views

README.md
Apparently the old events were causing some confusion as suggested in #130
=> Update migration docs with events

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
In our Sentry logging, we've occasionally, seen an error thrown that is `Illegal audioFocusRequest is null`. We haven't been able to reproduce, but believe that this is a race condition in our code that allows `disconnect` to be called before `connect` has been completed. We've been able to fix but adding guardrails in for this case, but figure that this change might also be helpful to prevent others from having same issue.
=> Handle case where audioFocusRequest is NULL

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, package.json
There are certain race conditions where localParticipant is not set and yet we get an onDisconnect.  Don't bother logging the participant to the event in these cases.
=> Move some dependencies into dev dependencies

docs/README.md
These docs threw me off because I wrote my code using `onParticipantDisabledTrack` instead of `onParticipantDisabledAudioTrack` and could not figure out why it was not working as intended. A better fix might be to also raise error or warning when using deprecated methods. But for now, updating the documentation might help future users.
=> Update docs to reflect enable/disable methods in version 2.0

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java, src/TwilioVideo.android.js
Currently, each time new instance of CustomTwilioVideoView created, it register life cycle event listener. So this PR will remove listener and release some static variables when component unmount.
Fix bug #95 
Please help to review!
=> [android] Release resource when unmounting

react-native-twilio-video-webrtc.podspec
This is to correct a fatal iOS bug.
Note that this version will still crash on an iOS simulator running iOS 13, but it should work fine on actual devices.
=> Updating TwilioVideo to 2.10.1

.gitignore, android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java, android/src/main/java/com/twiliorn/library/TwilioRemotePreviewManager.java, android/src/main/java/com/twiliorn/library/TwilioVideoPreviewManager.java
After upgrading to the latest Android SDK, @NonNull and @Nullable are undefined. This PR updates the references for @NonNull and @Nullable to come from `import androidx.annotation.*`
=> @NonNull @Nullable

jest/react-native-twilio-video-webrtc-mock.js
Many React Native applications nowadays use either Jest or Enzyme to performed automated testing. However, one challenge of these test frameworks is the difficulty testing native code. The approach commonly used by the @react-native-community libraries is to provide a mock file with the  component stubbed out and in some cases some basic functionality ([example](https://github.com/react-native-community/async-storage/blob/LEGACY/jest/async-storage-mock.js))
I've been using this mock with basic stubs for testing of our app that uses react-native-twilio-video and figured it might be good to add to the repo so that other users can get the same functionality.
=> feat: Jest mocks

android/build.gradle, android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java, ios/RCTTWVideoModule.m, package.json, src/TwilioVideo.android.js, src/TwilioVideo.ios.js
dataTracks for using Twilios 'UDP like' networking to send packets between clients.
onDataTrackMessageReceived, 
sendString, 
onParticipantAddedDataTrack, 
onParticipantRemovedDataTrack
iOS and android tested in a very complex activity based video call app.
No crashes, No errors on logcat, react native, gradle, xCode.
The only things I decided not to fully complete, and I don't really wish to:
- onParticipantAddedDataTrack/ onParticipantRemovedDataTrack the events don't have the most useful information, I didn't need that information.
- the dataTrack isn't part of the 'stats' report.
- sendString is only supported I didn't add sendData. As in react native it's very easy to stringify/parse a JSON object. Though maybe sendData is better performance I don't know.
=> dataTrack support added.

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
Prevent error trying ot unregister receiver when its already been unregistered. Happens frequently when app is in (or going to) background. IE
`2020-05-04 15:39:39.639 24200-24200/? W/System.err: java.lang.IllegalArgumentException: Receiver not registered: com.twiliorn.library.CustomTwilioVideoView$BecomingNoisyReceiver@bdf297f
2020-05-04 15:39:39.639 24200-24200/? W/System.err:     at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1271)
2020-05-04 15:39:39.639 24200-24200/? W/System.err:     at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1504)
2020-05-04 15:39:39.639 24200-24200/? W/System.err:     at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:659)
2020-05-04 15:39:39.640 24200-24200/? W/System.err:     at …
=> check myNoisyAudioStreamReceiver before unregistering

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
a.) Make the field `error` to be consistent with iOS.
b.) Get the proper message field from the exception.
=> Fix error message on android connect failure

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
When the call starts, the thumbnail of the front camera is not mirrored.
The camera should only mirror if it's not the back camera, however in the PR https://github.com/blackuy/react-native-twilio-video-webrtc/pull/24, the behavior was reversed to be be mirrored only if it's the back camera when `setThumbnailMirror` is called. That makes sense when switching the camera, because the camera is not changed synchronously, so when `setThumbnailMirror` is called, the camera source has not changed yet, so if it says it's the back camera, it will actually switch to the front camera, and it will be mirrored.
The issue is that `setThumbnailMirror` is also called when the thumbnail is registered on `registerThumbnailVideoView` and it sets mirror to false, because it's not the back camera.
The change …
=> Fix camera mirror on Android

ios/RCTTWVideoModule.m
Fixes a race condition where a local view which has already been mounted would not be mirrored if the video was started afterwards.
=> Update local view mirroring

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, ios/RCTTWVideoModule.m
Currently we do not actually unpublish the video when `setLocalVideoEnabled(false)` is called, we just stop it
The remote side is still getting that stream, it's just stuck. This PR makes it so that it's actually unpublished/republished so the remote side can handle it appropriately
Tested and worked on both iOS and Android
=> Actually unpublish video instead of pausing

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
Description:
iOS has `error` message in `onRoomDidDisconnect` event callback while android not having it. 
Similar issue: https://github.com/blackuy/react-native-twilio-video-webrtc/issues/290 (can't find any issue reported regarding `onRoomDidDisconnect`)
Tested this PR on android with `"error": "Room completed"` returned. (same as iOS, when room is terminated)
=> Add error message on android disconnected event

index.d.ts
Current types are only for iOS, Android does not have an object as its third param, and the roomName and encodingParameters are optional. This should fix the typing for Android + iOS.
=> TS: Fix connect params

ios/RCTTWVideoModule.m
If there is no video present on a device (like iOS simulator) and a user tries to perform any action of setLocalVideoEnabled (even setting it to false) causes a hanging promise. This sets localVideoTrack to false and resolves false.
=> Fix hanging promise video not present

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
iOS implementation at the moment includes local participant in participants array for the connect event and also triggers on participant connected event for itself. Android doesn't to it, it only takes remote participants into account.
With this PR I also add local participant for Android so it's consistent with iOS implementation.
iOS implementation reference is here: https://github.com/blackuy/react-native-twilio-video-webrtc/blob/master/ios/RCTTWVideoModule.m#L445
=> Include local participant for connect event on android

android/src/main/java/com/twiliorn/library/RNVideoViewGroup.java, android/src/main/java/com/twiliorn/library/TwilioRemotePreview.java, android/src/main/java/com/twiliorn/library/TwilioVideoPreview.java, android/src/main/java/com/twiliorn/library/TwilioVideoPreviewManager.java, src/TwilioVideoParticipantView.android.js
I've found that when the RotationAngle on the `onFrameDimensionsChanged` callback is any of `90` or `270`, the dimensions are inverted, e.g. if the other participant has a 720 (width) x 1280 (height) stream, the width and height in the `onFrameDimensionsChanged` are 1280 and 720 respectively.
I've been able to recreate this when calling from iOS Safari to a native android app. The participant in Safari sends a portrait stream, and the android app displays it as a landscape one with most of the content cropped.
The solution I found is to check the rotation angle and set the `videoWidth` and  `videoHeight` accordingly. This fixed the issue partially, because if the other participant rotates their device, the `RotationAngle` in `onFrameDimensionsChanged` changes, but `onLayout` is not …
=> Rotate video preview based on the VideoFrame.RotationAngle

Example/android/build.gradle, Example/android/gradle/wrapper/gradle-wrapper.properties, android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java, src/TwilioVideo.android.js, src/TwilioVideo.ios.js
Included in this PR:
- Gradle Upgrade (requested by Android Studio)
- Unnecessary binds in `TwilioVideo.ios.js` (the bound methods weren't using `this` anywhere in them, so bind was unnecessary)
- Add `{,un}publishLocal{Audio,Video}` methods for Android
Tested on S8+ to work as expected
Fixes https://github.com/blackuy/react-native-twilio-video-webrtc/issues/350
=> Publish/unpublish track methods for Android

ios/RCTTWVideoModule.m
Currently we create the `localDataTrack` in `connect` but never free the object, this causes ARC not to free up memory allocated for a room until the second time we call connect.
With this PR we free up the `localDataTrack` when the room disconnects in turn freeing up all memory allocated for a room.
=> iOS cleanup data track on disconnect

react-native-twilio-video-webrtc.podspec
This PR updates the pod for iOS 14 support. Full details on the change are here:
https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-3x
Basically it removes the need for a new NetworkPrivacyPolicy request and removes local networking for peer-to-peer rooms.
Tests locally on a localhost with two phones, works without a problem.
Solved #376
=> Update twilio-video-ios to 3.7 for iOS 14

Example/index.js, README.md
This fixes a bug in the README example where `_onParticipantRemovedVideoTrack` directly manipulates state and then replaces the videoTracks Map with an object. Turning videoTacks into an object causes errors when adding or removing more tracks.
Thanks for a great package! 🌟
=> README _onParticipantRemovedVideoTrack bugfix

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
Resolves https://github.com/blackuy/react-native-twilio-video-webrtc/issues/401
prevents video from enabling by default when backgrounding/re-opening the app
=> handles backgrounding/re-opening app with video disabled

Example/index.js, android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java, index.d.ts, ios/RCTTWVideoModule.m, src/TwilioVideo.android.js, src/TwilioVideo.ios.js
Adds support for Network Quality Reporting as per Twilio docs: https://www.twilio.com/docs/video/using-network-quality-api
I have tried to keep the changes as minimal as possible and add support for network quality reporting of local and remote participants.
Network Quality Reporting is disabled by default so existing users shouldn't see any difference unless explicitly enabled.
=> Add network quality reporting

Example/package.json, Example/yarn.lock
This change the import path of the SDK in the example to use the local path instead of the one on github.
I use this path whenever doing any development on the Example as with this change every time your run `yarn install` it uses the local version of the SDK instead of the one on Github.
This makes it much easier for development and generally makes sense for the Example as otherwise PR's would be untestable as the code on Github would not contain the changes that the Example code needs to run.
=> Reference local SDK in Example instead of the Github version

ios/RCTTWVideoModule.m
Previously we always created an enabled video track.  This PR updates it so that the video track is disabled by default, and only enabled during the connect process.
This also addresses a potential error where the camera may not be initialized.
=> Allow for initially disabled video tracks

index.d.ts, src/TwilioVideo.android.js
This PR fixes the following error in `index.d.ts` file
```
node_modules/react-native-twilio-video-webrtc/index.d.ts:93:46 - error TS7031: Binding element 'string' implicitly has an 'any' type.
93     onDataTrackMessageReceived?: ({ message: string }) => void;
~~~~~~
```                                                
NOTE: Also had to fix standard problems to pass CI tests. Let me know if you'd like it to be in a separate PR
=> fix onDataTrackMessageReceived type

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java, index.d.ts, src/TwilioVideo.android.js
This is a PR that I've been meaning to submit for about a year. Discussed in this issue https://github.com/blackuy/react-native-twilio-video-webrtc/issues/146#issuecomment-626987948
If `maintainVideoTrackInBackground` is set to true, the camera will not be released for usage by other applications while this app is in the background. Releasing the camera causes the video frame to freeze for some devices
=> fix: adding android variable for not releasing video in onHostPause

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, docs/README.md, index.d.ts, ios/RCTTWVideoModule.m
This PR includes:
- Addition of the trackSid of the remote data track on the onDataTrackMessageReceived event.
- Fix for Android where the track information that was being included in the onParticipantAddedDataTrack and onParticipantRemovedDataTrack events was the same as the information of the participant.
=> Add trackSid to the data track message received event and fix track information on Android

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java, index.d.ts, ios/RCTTWVideoModule.m, src/TwilioVideo.android.js, src/TwilioVideo.ios.js
This PR adds the `cameraType` option to the connect method, so that it can be used to start the video from either the front or back camera.
=> Add camera type to the connect options

src/TwilioVideo.ios.js
Currently the TwilioVideo will automatically initialize the camera upon mounting.  In certain applications this may not be desired.  This PR adds a new flag so that callers can disable the camera (and the need for any permissions).
=> Add autoInitializeCamera prop

Example/index.js, index.d.ts, src/TwilioVideo.android.js, src/TwilioVideo.ios.js
TypeScript definition file does not expose the dominant speaker feature. Add the connection param, and callback to enable this feature.
=> Add dominant speaker to the TypeScript definition

android/build.gradle
Fixes: #516 
- Changed minSdkVersion according to projects min sdk or by default (16) if there is no option in `rootProject`.
=> fix android minSdkVersion build error

Example/index.js
The variable name inside the `_onParticipantRemovedVideoTrack()` is conflicting with the outside variable name, this causes participants to disappear in the view
=> Example Project | Fixed bad setVideoTracks participant is removed

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
Right now on Android, once the `RNCustomTwilioVideoView` native component is instantiated, the voice call stream is automatically selected for volume control even if you're not in a room
This PR makes it so that it only happens when you have successfully connected to a room, and reverts back to the default volume control stream when you are not connected
The images below are after the code has been updated
Sorry for the noise in the diff, I formatted the file using Android Studio's `CTRL+ALT+L` (for windows), please let me know if you want them cleaned
=> [android] Remove stream voice control and only add them when they're connected

react-native-twilio-video-webrtc.podspec
Untested other than it didn't break my app ¯\\_(ツ)_/¯
This PR enables build support for iOS 9 & 10 with an upgrade to Twilio 4.6. iOS 9/10 support actually comes from Twilio Video 4.2, which restores ones ability to build apps for iOS 9 & 10 but the API itself does not actually allow video call usage on iOS 9 & 10. 
See [Twilio's Changelog notes](https://www.twilio.com/docs/video/changelog-twilio-video-ios-latest#420-january-27-2021)
=> Adds iOS 9 & 10 build support via Twilio Video 4.6

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java, android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java, docs/README.md, index.d.ts, src/TwilioVideo.android.js
I was facing the same issue reported here: https://github.com/blackuy/react-native-twilio-video-webrtc/issues/517 on an Android Pixel 6 Pro, a relatively new device. 
The issue stems from that some android devices do not fully support H264 codec, therefore video tracks from other participants could not be subscribed and throws an exception. 
I currently have the codec preference set for all my users to be ['H264', 'VP8'] from the web and other devices in a Small Group setting. Which means H264 will always be the codec negotiated by the Selective Forwarding Unit from Twilio if at least one participant has this preference.
According to Twilio Support, if I want to support Android Devices that do not have H264 support, I should change all the preferences to be ['VP8']. 
I want to continue …
=> Allow callback for H264 codec not support for Android Devices

android/build.gradle
> Support for 6.x will cease on September 17th, 2022. This branch will only receive fixes for critical issues until that date.
Link: https://www.twilio.com/docs/video/migrating-6x-7x
So far nothing important:
- the inclusion of `frames_encoded` in the returned data is not included in this PR
- I don't think the ordering of `onAudioTrackSubscribed` and `onVideoTrackSubscribed` ever mattered?
- [BREAKING] Minimum SDK will now be 21 instead of 16
- Update also bumped Google WebRTC to 1.0.32006 from 1.0.30039
Tested `ios -> android` and `web -> android`, was not able to test `android -> android` and multiple participants
| Device | OS Version | Twilio Version |
| ----------- | ----------- | ----------- |
| Huawei Y7a (PPA-LX2)  | EMUI 10.1.1 Android 10 | 7.3.1 |
| Galaxy A71 (SM-A715F/DS) | …
=> Upgrade TwilioVideo in Android to 7.3.1

Example/android/app/proguard-rules.pro, README.md, android/build.gradle, android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
This PR changes `CustomTwilioVideoView` import to use `tvi.webrtc` instead of `org.webrtc` and updates references to `org.webrtc` in different examples.
It solves https://github.com/blackuy/react-native-twilio-video-webrtc/issues/644 in which @slycoder was positive about the change. 
Have tested the code and it runs without issues for RN 0.68.5.
With this should I remove `jcenter()` from `/Example/android/build.gradle` as well?
=> Change org.webrtc to tvi.webrtc to fix #644

android/build.gradle
This updates TwilioVideo to 7.6.1. Which fixes issues with [How to fix apps with bad WebRTC versions](https://support.google.com/faqs/answer/12577537) that pops up when an app with `react-native-twilio-video-webrtc` gets when uploaded to Play Store.
The changelog for TwilioVideo: [Changelog](https://www.twilio.com/docs/video/changelog-twilio-video-android-v7#761-mar-27-2023). 
> The Twilio Programmable Video SDKs use [Semantic Versioning](http://www.semver.org/).
Which means that this update should contain no breaking changes.
Tested on `web -> android` and works without issues.
Other issues related to this warning: 
- This fixes #642 
- This fixes #672 
- Related https://github.com/twilio/video-quickstart-android/issues/731
=> Update TwilioVideo in Android to 7.6.1

README.md
Hi 👋 Thanks for creating the config plugin for Expo!
We recommend developers use the `npx expo` command for any Expo SDK package. It uses local/versioned [Expo CLI](https://docs.expo.dev/more/expo-cli/) and is tailored for each SDK version because it installs compatible package versions depending on the SDK version.
I saw your tweet about the config plugin PR and was going through the docs and thought this could be a nice enhancement. Sometimes, installing an Expo SDK package using `npm` or `yarn` might lead to incompatibility between Expo SDK's version and the package's version. We (at Expo) also follow the same pattern for installation instructions so that developers do not run into this issue. Example: https://docs.expo.dev/versions/latest/sdk/build-properties/#installation
By updating …
=> docs: Update expo-build-properties installation command
