TwilioVideo.js
ios/TWVideoModule.m

This allows people to disable their video or mute their audio. In my use case I needed to be able to let the user turn off their video, and mute themselves.

Adds the ability to remove and add tracks at will.

---

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java
src/TwilioVideo.android.js

* Add events for participants adding/removing video tracks.
* Support enabling/disabling capturers in the same way as iOS.
* Rename a number of methods in the javascript library to match the
names used on iOS.

Bring the android closer inline to the iOS reference implementation

---

Example/index.android.js
android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java
src/TwilioVideo.android.js

1) Fixed bug in CustomTwilioVideoView.java where onConnected was used in the Events interface list instead of onRoomDidConnect
2) Added feature to support room name during connect

Events bug fix and added support for room name during connect

---

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
android/src/main/java/com/twiliorn/library/RNVideoViewGroup.java

Tried the video chat. During the course of the chat, I flipped the camera from front to back. The mirroring was not fine. Fixed this.

Changed mirroring logic to apply only for back camera

---

README.md

Mention the solution for #21 and #27

Update android docs

---

android/build.gradle
android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java

Remove a couple of unused android deps …These aren't needed so let's not link them in, plus they may lead to needing various hacks to get things to work.  (See #27)

Remove android deps

---

README.md

**Changes Made:**
- Fixed broken links for Known Issues in the README.md.

README - fix broken links to known iOS issues

---

README.md

Mention proguard in android instructions

---

ios/RCTTWSerializable.h
ios/RCTTWVideoModule.h

Sorry, my previous PR accidentally omitted to header file changes.

Fix iOS build

---

README.md

Mention installing entirely via podspec, and also mention updating header paths.

Update Pod install docs

---

ios/RCTTWVideoModule.m
src/TwilioVideo.ios.js

See #123 
iOS only. Unfortunately my project only uses iOS and my Java skills are not the best.

Feature locally mute remote audio

---

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java

Android Fix for issue #164
Also need to update build.gradle to api 27
Here ===> https://github.com/blackuy/react-native-twilio-video-webrtc/pull/181
The issue is on both android and ios, but i'll write how to reproduce it easily on android:
1. Open your app and push the volume button. You should have normal volume control (notifications volume for example)
2. Start a call using `<TwilioVideo />`
3. Change the volume, it should now control the "Call" volume
4. Exit the current screen, un-mounting the `<TwilioVideo />` component. Call `.disconnect()` on your screen's `componentWillUnmount()` function.
5. The call stops. Press the volume button. You are still controlling the 'Call' Volume. It still ducks/stops any other audio media playing.
6. Press home button to exit the app. Press volume. …

setAudioFocus on disconnect, implemented api > 26

---

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
circle.yml
ios/RCTTWVideoModule.m

 Add room sid to various room-related events

---

docs/README.md
ios/RNTwilioVideoWebRTC.xcodeproj/project.pbxproj

ADD: setLocalVideoEnabled & setLocalAudioEnabled to the docs

---

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java

Fix issue #102 
Please help to review!

[android] init local video view when initializing native view

---

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java

**### Solves issue(s)**
Prevent crash: #217

[android] preventing crash on new CameraCapturer by putting it in try catch block

---

Example/babel.config.js
Example/package.json
Example/yarn.lock
package.json
src/TwilioVideo.android.js
src/TwilioVideo.ios.js
src/TwilioVideoLocalView.ios.js
src/TwilioVideoParticipantView.ios.js
yarn.lock

Things were getting stale so I thought it'd be advisable to keep things up-to-date.

Update a bunch of packages

---

README.md

I ran into the same issues as mentioned in https://github.com/blackuy/react-native-twilio-video-webrtc/issues/92#issuecomment-441358693
Hope this clears things up a bit.

Improve iOS setup process section in README

---

index.d.ts
package.json
yarn.lock

Resolves #267  by adding index.d.ts

Typings For Twilio video

---

android/build.gradle
android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
android/src/main/java/com/twiliorn/library/PatchedVideoView.java
android/src/main/java/com/twiliorn/library/RNVideoViewGroup.java
ios/RCTTWLocalVideoViewManager.m
ios/RCTTWRemoteVideoViewManager.m
ios/RCTTWVideoModule.m
react-native-twilio-video-webrtc.podspec
src/TwilioVideo.ios.js

Upgrade to TwilioVideo v3 on iOS

---

README.md

Fixes https://github.com/blackuy/react-native-twilio-video-webrtc/issues/304

Document minimum iOS Deployment Target

---

Example/android/app/proguard-rules.pro
README.md

See https://github.com/blackuy/react-native-twilio-video-webrtc/issues/308

Update proguard rules 

---

Example/.babelrc
Example/index.js
Example/ios/Example.xcodeproj/project.pbxproj
Example/ios/Example.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
Example/ios/Example/AppDelegate.m
Example/ios/Podfile
Example/ios/Podfile.lock
Example/package.json
Example/yarn.lock

Includes numerous fixes to get things up to date, as well as removes the roomName from the form as that is no longer needed.

Loads of fixes for the iOS example

---

docs/README.md
index.d.ts

Fix trackIdentifier type

---

README.md
ios/RCTTWVideoModule.m

Fix for video frozen after returning from background

Fix for video frozen

---

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
ios/RCTTWVideoModule.m

This resolves https://github.com/blackuy/react-native-twilio-video-webrtc/issues/330

Prevent re-joining participants when local video is disabled/enabled

---

index.d.ts

This method is currently missing and might cause some confusion for beginners.

TS: Include toggleSoundSetup

---

Example/android/app/build.gradle
Example/android/app/proguard-rules.pro
Example/android/app/src/main/AndroidManifest.xml
Example/android/app/src/main/java/com/example/MainApplication.java
Example/android/app/src/main/res/xml/network_security_config.xml
Example/android/build.gradle
Example/android/gradle.properties
Example/android/gradle/wrapper/gradle-wrapper.properties
Example/android/settings.gradle
Example/index.js

This extends the changes introduced by #282 and makes them work also on Android 9+ devices.
This has been tested to work correctly on an Android 9 device.

Fix android example

---

android/build.gradle

In testing locally with my team, we have noticed increased stabilization in our android app with the version increase and no breaking changes.

Update twilio:video-android version to 5.10

---

android/build.gradle

this PR for fix an issues [https://github.com/blackuy/react-native-twilio-video-webrtc/issues/372](https://github.com/blackuy/react-native-twilio-video-webrtc/issues/372)

fix google webrtc version change

---

Example/android/gradle.properties

Turn on android X for the example

---

README.md

In the **Usage part** of the README.
I converted the example code from a Class Component to Function Component.
So it will be **up-to-date** and **Hooks** can be used with it.

[README] Converted Class Component to Function Component

---

Example/index.js

Fixes issues in the example app.
Without these changes the example app doesn't run.

Fixes the example app

---

index.d.ts

Fixes incorrect typescript definitions that were introduced in #406

Fix typescript definitions

---

android/build.gradle

Updating in order to address #417

Bump android dependency

---

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java
ios/RCTTWVideoModule.m
src/TwilioVideo.android.js
src/TwilioVideo.ios.js

This feature implements ios/android twilio dominant speaker handlers

Dominant speaker enabled feature

---

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
docs/README.md
index.d.ts
ios/RCTTWVideoModule.m

This makes it easier to identify the local participant when the room is connected.

Add local participant to onRoomDidConnect

---

src/TwilioVideo.ios.js

https://github.com/blackuy/react-native-twilio-video-webrtc/issues/467

replace componentWillMount with componentDidMount

---

android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
ios/RCTTWVideoModule.m
src/TwilioVideo.ios.js

This PR allows users to connect to the Twilio room with the audio disabled.

Add enableAudio as a connection option

---

index.d.ts

Add autoInitializeCamera prop to typedef

---

android/src/main/AndroidManifest.xml
android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java

Added bluetooth support for android devices.
An updated version of: https://github.com/blackuy/react-native-twilio-video-webrtc/pull/498

Add Android Bluetooth Support

---

index.d.ts
package.json

Adds 'applyZOrder' to types addressing https://github.com/blackuy/react-native-twilio-video-webrtc/issues/628

add applyZOrder to types

---

Example/index.js
ios/RCTTWVideoModule.m
src/TwilioVideo.ios.js

feat: Allow user to share screen on iOS through In app capture method 

---

Example/index.js
README.md

When react's set state hook depends on past values, a callback is recommendend

Added call back for react setState hook
